server:
  port: 8080

spring:
  application:
    name: starfish
  data:
    redis:
      host:
      password:
      port: 6379
      username: default
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: xxx
    url: jdbc:mysql://127.0.0.1:3306/xxx?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: xxx
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 8
        keep-alive: 60s
        max-size: 8
        queue-capacity: 2147483647
      shutdown:
        await-termination: true
        await-termination-period:
      thread-name-prefix: task-

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: admin
      paths-to-match:
        - /api/admin/**
    - group: public
      paths-to-exclude:
        - /api/admin/**
      paths-to-match:
        - /api/**
  packages-to-scan: com.starfish.core.controller
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

starfish:
  cache:
    enabled: true
    expire: 3600
  datasource:
    enabled: true
  elapsed-time:
    enabled: false
  exception:
    enabled: true
  executor:
    corePoolSize: 10
    enabled: false
    keepAliveSeconds: 60
    maxPoolSize: 10
    queueCapacity: 2147483647
    rejectedExecutionHandler: java.util.concurrent.ThreadPoolExecutor$AbortPolicy
  minio:
    access-key: yLYYn14VnYcdLyOnOY12
    bucket-name: my-bucket-dev
    enabled: false
    endpoint: http://127.0.0.1:9000
    expire: 3600
    secret-key: OZGbQ31lTGptvH1Io6Wc5wfKfwvMxuQvuOZA3TtZ
  push:
    pushdeer:
      base-url: https://api2.pushdeer.com
      enabled: false
      message-push-url: /message/push
    bark:
      base-url: https://api.day.app
      enabled: true
      message-push-url: /push
  response-wrapper:
    enabled: false
