name: MavenDeploy

# 如果需要打快照包，可以把代码合并到dev分支，会触发MavenDeploy.yml工作流自动打包
on:
  push:
    branches:
      - "main"
      - "dev"
#      - "2.3.x"
#      - "*"
#  schedule:
#    - cron: '0 2 * * *'

env:
  APPLICATION_NAME: "starfish"
#  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  MavenDeploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Package
        run: mvn --batch-mode --update-snapshots package -Dmaven.test.skip=true

      - name: Deploy
        env:
          MAVEN_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: mvn --batch-mode --update-snapshots deploy -Dmaven.test.skip=true