name: MavenDeploy

on:
  push:
    branches:
      - "main"
      - "dev"
      - "*"
#  schedule:
#    - cron: '0 2 * * *'

env:
  APPLICATION_NAME: "starfish"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

#  APPLICATION_VERSION: "1.0.0"
#  APPLICATION_ENV: "dev"

jobs:
  MavenDeploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Package
        run: mvn --batch-mode --update-snapshots package -Dmaven.test.skip=true

#      - name: Install
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#        run: mvn --batch-mode --update-snapshots install -Dmaven.test.skip=true

      - name: Deploy
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: mvn --batch-mode --update-snapshots deploy -Dmaven.test.skip=true

#  - name: Build With Maven
#      run: mvn --batch-mode --update-snapshots clean package -Dmaven.test.skip=true
#      env:
#        MAVEN_PASSWORD: ${{ secrets.PACKAGES_TOKEN }}

#      - name: Deploy
#        uses: easingthemes/ssh-deploy@v2.2.11
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.TENCENT_SERVER_PRIVATE_KEY }}
#          ARGS: "-rltgoDzvO --delete"
#          SOURCE: "target/starfish-1.0.0-SNAPSHOT.jar"
#          REMOTE_HOST: "101.34.149.151"
#          REMOTE_USER: "root"
#          TARGET: "/opt/starfish"
